/**
 * Regenerates src/version.ts from package.json.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const TARGET = path.join(ROOT, 'src', 'version.ts');

const { version } = require(path.join(ROOT, 'package.json'));

if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  console.error(`sync-version: package.json version is not semver: ${version}`);
  process.exit(1);
}

const contents = `/**
 * Generated by scripts/sync-version.js. Edit package.json instead.
 */
export const VERSION = '${version}';
`;

const existing = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, 'utf-8') : null;

if (existing === contents) {
  process.exit(0);
}

fs.writeFileSync(TARGET, contents);
console.log(`sync-version: src/version.ts -> ${version}`);
